### ISSUE TITLE
Node ABI Compatibility With Older Linux

### ISSUE THREAD

**Issue by jscottandersonthe1** [andrewlow/node#56]
I've got a primitive kernel to which I am handcuffed, linux 2.6.21 running on a ppc603 core.  I've built v8 and can run the d8 shell on the target system, but now that I've cross-compiled node, it is looking for the standard c library and does not find GLIBC_2.7.  I installed a newer library in an alternative location, but the OS ABI is invalid.  I think what I need to do is build node with the library included (static linking?), but thought I'd done that.  Any thoughts?

Note, I've made changes to deps/v8ppc to bring in the g4compat changes and everything builds without complaint.
git status gives: On branch v0.10.38-release-ppc

**Comment by andrewlow** [comment]
Weird, if you've got d8 working - then you're certainly able to get the hard part working.

It's possible you've gotten tripped up with the integration of your changes with the node build system? Unfortunately I don' think there is enough information for me to make a good guess as to your exact problem.

**Comment by jscottandersonthe1** [comment]
I'm thinking it's my relative ignorance of library dependencies.  I built both images using my home built tool chain.  It seems that d8 does not need anything that is not provided by my primitive libraries whereas node does.  Here's what ldd reports for node and for d8:

       root@10.113.131.73:~# ldd -d -r -v node
       ./node: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./node)
                linux-vdso32.so.1 =>  (0x00100000)
                libdl.so.2 => /lib/libdl.so.2 (0x0ffdc000)
               librt.so.1 => /lib/librt.so.1 (0x0ffb4000)
               libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0feaf000)
               libm.so.6 => /lib/libm.so.6 (0x0fdee000)
               libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0fdbb000)
               libpthread.so.0 => /lib/libpthread.so.0 (0x0fd83000)
               libc.so.6 => /lib/libc.so.6 (0x0fc1c000)
               /lib/ld.so.1 (0x30000000)
       symbol __isoc99_sscanf, version GLIBC_2.7 not defined in file libc.so.6 with link time reference (./node)

        Version information:
        ./node:
                libgcc_s.so.1 (GCC_3.4) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_4.2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GLIBC_2.0) => /lib/libgcc_s.so.1
                librt.so.1 (GLIBC_2.2) => /lib/librt.so.1
                libdl.so.2 (GLIBC_2.0) => /lib/libdl.so.2
                libdl.so.2 (GLIBC_2.1) => /lib/libdl.so.2
                libm.so.6 (GLIBC_2.1) => /lib/libm.so.6
                libm.so.6 (GLIBC_2.0) => /lib/libm.so.6
                libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
                libc.so.6 (GLIBC_2.7) => not found
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
                libpthread.so.0 (GLIBC_2.6) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.3.3) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.2) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.1) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.0) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.3.2) => /lib/libpthread.so.0
        /lib/libdl.so.2:
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/libc.so.6
        /lib/librt.so.1:
                libpthread.so.0 (GLIBC_2.1) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.2) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.6) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_PRIVATE) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.0) => /lib/libpthread.so.0
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /usr/lib/libstdc++.so.6:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                libgcc_s.so.1 (GCC_4.2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.3) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_4.1.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GLIBC_2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/libgcc_s.so.1
                libm.so.6 (GLIBC_2.4) => /lib/libm.so.6
                libm.so.6 (GLIBC_2.0) => /lib/libm.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
        /lib/libm.so.6:
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libgcc_s.so.1:
                ld.so.1 (GLIBC_2.1) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libpthread.so.0:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                ld.so.1 (GLIBC_2.1) => /lib/ld.so.1
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libc.so.6:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1

       root@10.113.131.73:~# ldd -d -r -v d8
               linux-vdso32.so.1 =>  (0x00100000)
               libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0fefb000)
               libm.so.6 => /lib/libm.so.6 (0x0fe3a000)
               libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x0fe07000)
               libpthread.so.0 => /lib/libpthread.so.0 (0x0fdcf000)
               libc.so.6 => /lib/libc.so.6 (0x0fc68000)
               /lib/ld.so.1 (0x30000000)

        Version information:
        ./d8:
                libgcc_s.so.1 (GCC_3.4) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_4.2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GLIBC_2.0) => /lib/libgcc_s.so.1
                libm.so.6 (GLIBC_2.1) => /lib/libm.so.6
                libm.so.6 (GLIBC_2.0) => /lib/libm.so.6
                libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
                libpthread.so.0 (GLIBC_2.6) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.2) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.1) => /lib/libpthread.so.0
                libpthread.so.0 (GLIBC_2.0) => /lib/libpthread.so.0
        /usr/lib/libstdc++.so.6:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                libgcc_s.so.1 (GCC_4.2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.3) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_4.1.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GLIBC_2.0) => /lib/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/libgcc_s.so.1
                libm.so.6 (GLIBC_2.4) => /lib/libm.so.6
                libm.so.6 (GLIBC_2.0) => /lib/libm.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
        /lib/libm.so.6:
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libgcc_s.so.1:
                ld.so.1 (GLIBC_2.1) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libpthread.so.0:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                ld.so.1 (GLIBC_2.1) => /lib/ld.so.1
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1
                libc.so.6 (GLIBC_2.1.3) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.1) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.2) => /lib/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/libc.so.6
                libc.so.6 (GLIBC_2.0) => /lib/libc.so.6
        /lib/libc.so.6:
                ld.so.1 (GLIBC_2.3) => /lib/ld.so.1
                ld.so.1 (GLIBC_PRIVATE) => /lib/ld.so.1

**Comment by andrewlow** [comment]
Node is a different beast than V8 in terms of how it's built.

Node also includes libuv - which helps abstract out a lot of OS stuff, the dependency might be coming from it. Similarly it optionally (but by default) includes openssl which may be pulling in things.

You commented that you had 'statically linked' in the libraries to V8 (d8), but it really doesn't look like that's is true from the output of 
```ldd -d -r -v d8```

Here is how I'd approach the problem. Start digging into the object files to figure out which one has caused the __isoc99_sscanf, GLIBC_2.7 dependency. Then address that issue. I usually end up figuring out how to use a "find exec" via google which let's me do a big recursive search.

**Comment by jscottandersonthe1** [comment]
@andrewlow  Thanks Andrew.  ssl is where that symbol comes in.  My only problem now is that the cross build complains that it can't find a necessary header file when I compile after configuring using --without-ssl.

       In file included from ../src/node.cc:85:0:
       ../src/node_crypto.h:30:25: fatal error: openssl/ssl.h: No such file or directory
        #include <openssl/ssl.h>

I had to remove an unconditional reference to node_crypto.h and comment out some references to the SSL2 and SSL3 symbols, a little messy, but it built.  Now I'm back to hitting an illegal instruction so I need to look at my merge.  I merged the g4compat branch from v8ppc into deps/v8ppc, then changed the Makefile to reference that instead of deps/v8.  Will report success.

**Comment by jscottandersonthe1** [comment]
Merge and change summary so far:

       #	modified:   Makefile
       #	modified:   common.gypi
       #	modified:   configure
       #	modified:   deps/v8ppc/src/ppc/assembler-ppc.cc
       #	modified:   deps/v8ppc/src/ppc/code-stubs-ppc.cc
       #	modified:   deps/v8ppc/src/ppc/code-stubs-ppc.h
       #	modified:   deps/v8ppc/src/ppc/constants-ppc.h
       #	modified:   deps/v8ppc/src/ppc/lithium-codegen-ppc.cc
       #	modified:   deps/v8ppc/src/ppc/macro-assembler-ppc.cc
       #	modified:   deps/v8ppc/src/ppc/macro-assembler-ppc.h
       #	modified:   deps/v8ppc/src/v8globals.h
       #	modified:   node.gyp
       #	modified:   src/node.cc
       #	modified:   src/node_constants.cc
       #	modified:   tools/wrk/Makefile

**Comment by jscottandersonthe1** [comment]
Limited tools for platform.  This is my offline gdb output:

       Core was generated by `./node'.
       Program terminated with signal 4, Illegal instruction.
       #0  0x33f35bac in ?? ()

**Comment by jscottandersonthe1** [comment]
Another question.  Here is the configure that I execute before cross-compiling:

       ./configure --without-snapshot --without-ssl --without-ssl2 --without-ssl3 --dest-cpu=ppc

I also went in and hard-coded byte order to "big" in the configure script.  Here is the result:
[config.gypi.txt](https://github.com/andrewlow/node/files/86191/config.gypi.txt)

I cannot see where that illegal instruction might have come from.  Still looking.

**Comment by andrewlow** [comment]
I'd guess that the illegal instruction is some code that v8 has generated by compiling javascript code..

**Comment by jscottandersonthe1** [comment]
Not clear on that issue.

       root@10.113.131.73:~# ./d8
       V8 version 3.14.5 (candidate) [console: dumb]
       d8> Math.sqrt(0.01);
       0.1
       d8> quit();
       root@10.113.131.73:~# ./node
       Illegal instruction (core dumped)

This is what I'd see with d8 before I built the g4compat branch.  I have to presume at this point that my merge missed something.  It's just I can't seem to make sense of the opcodes that the core dump comes back with.  Definitely moving forward though and appreciate the help.

**Comment by andrewlow** [comment]
I'm a bit confused.

You've got evidence you can run d8 on the target hardware. This is good.

> before I built the g4compat branch

So things changed? You should be able to take the 'working' V8 code that built d8, and bulk copy it over into the Node build -- and then make that work (there may be a little fiddling to get the build scripts to work)

If you had 'merge' problems, you're probably only a diff or two away from discovering them.

**Comment by jscottandersonthe1** [comment]
Before I "discovered" the g4compat branch of v8ppc, I was getting core dumps on illegal instructions.  I was able to find the offending instructions and comment them out, but that was obviously not a solution.  When I asked about substitutes, tunniclm (Mike) pointed me to a solution he'd already put together, the magical g4compat branch.

I thought I'd get really clever and compile v8 (g4compat) as a shared library and compile node to use that.  I demonstrated to myself that I could install d8 and the resulting .so file on my board and it worked, but I have not yet figured out the magic for building node node to use that shared object.  My cross ld chokes on "cannot find -lv8" and I apparently don't know how that works since my efforts have always ended up the same there.

I'll dig back in to that "merge tomorrow. I saw another note in which you @andrewlow  noted that simply cloning the g4compat branch into deps/v8 would not work.  What I did was merge the g4compat diffs from the mainline into deps/v8ppc, then renamed deps/v8ppc to deps/v8 (after moving the old deps/v8 under another name).  I feel this is close.  Thanks so much for the encouragement.

**Comment by andrewlow** [comment]
> I saw another note in which you @andrewlow noted that simply cloning the g4compat branch into deps/v8 would not work

Hmm, well past me was probably right. It's been a while since I was splunking in this code but it is possible you also took something out of context. The node source tree does have a copy of v8 inside of it.

I agree you're close -- but _something_ isn't quite right yet. Keep at it.

**Comment by jscottandersonthe1** [comment]
Well, I can report that I've got node running on my system and the only issue in migrating the g4compat branch of v8ppc to my dependencies was the CpuFeatures::Probe which was not looking for ppc603.  All I had to do was add that test and the 64-bit instructions are no longer encountered.  Thanks for all your hard work here.  Now I can really get myself into some trouble.  ;-)

**Comment by andrewlow** [comment]
Glad you got it working - is this captured in a fork somewhere? It'd be great to link it here in case others want to benefit from the work you've done.

**Comment by jscottandersonthe1** [comment]
I'm in the process of figuring out how to do that being a complete newbie to git.

    On Thursday, January 14, 2016 10:13 AM, Andrew Low <notifications@github.com> wrote:
 

 Glad you got it working - is this captured in a fork somewhere? It'd be great to link it here in case others want to benefit from the work you've done.—

**Comment by jscottandersonthe1** [comment]
One more update in case anyone is interested.  My platform is an MPC8378E processor (e300c4 core) running a 2.6.21 kernel.  As mentioned before, it was mostly a matter of finding the right v8 branch (g4compat) and merge that in to the deps/v8ppc directory to get a running build.  I also had to add a check for ppc603, but I was still stuck on a dependency introduced by deps/openssl

       symbol __isoc99_sscanf, version GLIBC_2.7

when I tried to execute node on my target board.

I was able to build a runnable node by configuring --without-ssl, but that turned out to be pretty useless because npm is utterly dependent on the crypto library from openssl.

To fix that I copied a small piece from the deps/cares/cares.gyp file into the deps/openssl/openssl.gyp file.  This 'defines' snippet gave me the symbol _GNU_SOURCE which results in the build not using the symbol __isoc99_sscanf.

I'm still puzzling over how best to capture this information in a branch and whether/how it should be included in the dependencies here in the node repository.  I'm willing to do the work, but I'll have to formulate a good plan first.  Suggestions are welcome.

**Comment by andrewlow** [comment]
I'd simply "fork" this github repo - which will create a git repo that is under your github user.

Best to pick the closest branch from this repo that matches what you want to build (node version, etc)

Then apply the same set of changes you used to succeed, and commit them to your repo.

Update the Readme.md to indicate the build environment etc - so that others finding the repo have a hope of replicating what you did.

**Comment by jscottandersonthe1** [comment]
I've forked from 10.38-release-ppc.  Repository is at https://github.com/jscottandersonthe1/node.git

 I hope this can be useful to anyone trying to solve a similar problem.

**Comment by jscottandersonthe1** [comment]
Closing because I consider the ABI issue solved with the changes detailed in the forked repository.

**Comment by andrewlow** [comment]
:+1: thanks @jscottandersonthe1
